name: Auto Assign PR Creator

on:
  pull_request:
    types: [opened]

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    steps:
      - name: Assign PR to Creator
        uses: actions/github-script@v7
        with:
          script: |
            const creator = context.payload.pull_request.user.login;

            await github.rest.issues.addAssignees({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              assignees: [creator]
            });
